services:
  - name: skynet-backend
    type: web
    build:
      dockerfile: Dockerfile
    envs:
      - key: DB_PATH
        value: /app/data/skynet_db.sqlite
      - key: MODEL_PATH
        value: /app/src/data/model.pkl
      - key: VIRUSTOTAL_API_KEY
        value: YOUR_VIRUSTOTAL_KEY
      - key: TWILIO_ACCOUNT_SID
        value: YOUR_TWILIO_SID
      - key: TWILIO_AUTH_TOKEN
        value: YOUR_TWILIO_AUTH_TOKEN
      - key: TWILIO_WHATSAPP_NUMBER
        value: whatsapp:+14155238886
      - key: WHATSAPP_NUMBER
        value: whatsapp:+6281234567890
    volumes:
      - source: skynet-data
        target: /app/data
    startCommand: gunicorn -w 1 -b 0.0.0.0:8080 --timeout 120 src.app:app
  - name: redis
    type: database
    image: redis:latest
volumes:
  - name: skynet-data
    path: /app/data